groups:
  - name: ui
    description: UI translations
  - name: reports
    description: Translations of report title and descriptions
  - name: errors
    description: Translations of errors
languages:
  - name: English
    locale: en
  - name: Greek
    locale: gr
translations:
  ################################################################################
  # ENGLISH translations
  ################################################################################
  - group: ui
    locale: en
    keys:
      - login: login
      - register: register
      - welcome: Welcome
      - bestUi: BestUiEu
      - signUp: Sign Up
      - plEnterName: Enter Name
      - plEnterEmail: Enter Email
      - plEnterUserName: Enter Username
      - plEnterPassword: Enter Password
      - plEnterRepeatPassword: Repeat Password
      - btnCancel: Cancel
      - btnSignup: Sign Up
      - signIn: Sign In
      - plEnterUsernameSignInForm: username
      - plEnterUsernameSignInForm: password
      - btnSignIn: Sign In
      - logOut: logout
      - changePassword: changePassword
      - checkYourBooks: Check Your Books
      - title: Title
      - author: Author
      - addBook: Add Book
      - deleteBook: Delete Book


  - group: errors
    locale: en
    keys:
      - warn: Warning
      - unexpected_error: An unexpected error has occurred.
      - login_failure: Login failed due to invalid credentials, please try again
        forceUpdate: true
        #forceUpdate flag is used to change a value of existing key
  ################################################################################
  # Greek translations
  ################################################################################
  - group: ui
    locale: gr
    keys:
      - login: Sundesi
      - register: Eggrafh
      - welcome: Kalws Hrthate
      - bestUi: kaliterhEmfanishEuropis
      - signUp: Eggrafeite
      - plEnterName: Eisagete Onoma
      - plEnterEmail: Eisagete Email
      - plEnterUserName: Eisagete onoma xrhsth
      - plEnterPassword: Eisagete kodiko
      - plEnterRepeatPassword: epanalavete kodiko
      - btnCancel: akyrosi
      - btnSignup: egrafeite
      - signIn: sundetheite
      - plEnterUsernameSignInForm: onoma xrhsth
      - plEnterUsernameSignInForm: kodikos
      - btnSignIn: sundetheite
      - logOut: aposindesi
      - changePassword: allahKodikou
      - checkYourBooks: des ta vivlia sou
      - title: titlos
      - author: suntakths
      - addBook: prosthese vivlio
      - deleteBook: diegrapse vivlio
  - group: reports
    locale: gr
    keys:
      - reports_dir: Répertoire des rapports
  - group: errors
    locale: gr
    keys:
      - warn: Attention
      - unexpected_error: Une erreur imprévue s'est produite
      - login_failure: La connexion a échoué en raison d'informations d'identification non valides