groups:
  - name: ui
    description: UI translations
  - name: reports
    description: Translations of report title and descriptions
  - name: errors
    description: Translations of errors
languages:
  - name: English
    locale: en
  - name: Greek
    locale: gr
translations:
  ################################################################################
  # ENGLISH translations
  ################################################################################
  - group: ui
    locale: en
    keys:
      - login: Login
      - register: Register
      - welcome: Welcome
      - signUp: Sign Up
      - enterName: Enter Name
      - enterEmail: Enter Email
      - enterUsername: Enter Username
      - enterPassword: Enter Password
      - repeatPassword: Repeat Password
      - cancel: Cancel
      - signIn: Sign In
      - username: username
      - password: password
      - logOut: logout
      - changePassword: changePassword
      - bookList: BookList
      - title: Title
      - author: Author
      - addBook: Add Book
      - deleteBook: Delete Book
      - enterTitle: Enter Title
      - enterAuthor: Enter Author
      - currentPassword: Current Password
      - newPassword: New Password
      - translations: Translations
      - save: Save
      - greek: Greek
      - english: English
      - keyName: KeyName
      - update: Update
      - updateTranslations: Update Translations
      - showList: showList
      - selectLanguage: Select Language
  ################################################################################
  # GREEK translations
  ################################################################################
  - group: ui
    locale: gr
    keys:
      - login: Σύνδεση
      - register: Eγγραφή
      - welcome: Καλώς ήρθατε
      - signUp: Εγγραφείτε
      - enterName: Εισάγετε όνομα
      - enterEmail: Εισάγετε email
      - enterUsername: Εισάγετε ονομά χρήστη
      - enterPassword: Εισάγετε κωδικό
      - repeatPassword: Επαναλάβετε κωδικό
      - cancel: Ακύρωση
      - signIn: Συνδεθείτε
      - username: Όνομα χρήστη
      - password: Κωδικός
      - logOut: Αποσύνδεση
      - changePassword: Αλλαγή Κωδικού
      - bookList: Λίστα βιβλίων
      - title: Τίτλος
      - author: Συντάκτης
      - addBook: Πρόσθεσε  βιβλίο
      - deleteBook: Διέγραψε βιβλίο
      - enterTitle: Εισάγετε τίτλο
      - enterAuthor: Εισάγετε συντάκτη
      - currentPassword: Tρέχων Κωδικός
      - newPassword: Καινούργιος Κωδικός
      - translations: Μεταφράσεις
      - save: Αποθήκευση
      - greek: Ελληνικά
      - english: Αγγλικά
      - keyName: Όνομα Κλειδιού
      - update: Ενημέρωση
      - updateTranslations: Ενημέρωση Μεταφράσεων
      - showList: Δές την λίστα
      - selectLanguage: Διάλεξε Γλώσσα

